### ISSUE TITLE
Two sum problem in Python

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#30]
Given an array of integers `numbers` and an integer `sum`, return indexes of the two numbers such the sum of two numbers is equal to `sum`.

**Assumpttion**

- Each input would have exactly one solution, 
- You should not not use the same element twice.
- Return the indexes in any order.

Explain different approaches in Python Language

**Comment by mallikpramod** [comment]
i would like to take this issue, please assign me

**Comment by arungudelli** [comment]
@mallikpramod give me some time I will assign

**Comment by mallikpramod** [comment]
please tell me where exactly i should commit the file

**Comment by 7oSkaaa** [comment]
I Can take it, with different approaches.

**Comment by arungudelli** [comment]
Hi @7oSkaaa 

Can you take up another issue  [https://github.com/arungudelli/python.shiksha/issues/33](https://github.com/arungudelli/python.shiksha/issues/33)

**Comment by arungudelli** [comment]
@mallikpramod  

Please read and follow the steps mentioned

https://github.com/arungudelli/python.shiksha/blob/main/CONTRIBUTING.md

and

https://github.com/arungudelli/python.shiksha/blob/main/README.md

**Comment by mallikpramod** [comment]
@arungudelli there is no problems folder inside **content/en/** inside this directory can you please verify again

**Comment by arungudelli** [comment]
@mallikpramod  

It's there please try to do git pull and check 

have you taken the proper branch name `30-two-sum-problem-in-python-1`

https://github.com/arungudelli/python.shiksha/tree/30-two-sum-problem-in-python-1/content/en/problems
