### ISSUE TITLE
Roman to Integer

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#33]
Given a Roman literals, convert it into an integer in Python

**Assumptions:**

- 1 <= input.length <= 15
- `input` contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').
- `input` is a valid roman numeral in the range [1, 3999].

Explaine the different ways to solve the problem with time and space complexity (if applicable)

**Comment by 7oSkaaa** [comment]
Ok, It's good for me

**Comment by arungudelli** [comment]
Please read and follow the steps mentioned 

https://github.com/arungudelli/python.shiksha/blob/main/CONTRIBUTING.md 

and 

https://github.com/arungudelli/python.shiksha/blob/main/README.md

**Comment by Faizan96322** [comment]
hey, I would like to contribute to this repo....please assign me this task!

**Comment by arungudelli** [comment]
@Faizan96322 Can you work on this? 
https://github.com/arungudelli/python.shiksha/issues/37

**Comment by rohit172001-eng** [comment]
Hi @arungudelli, I would like to contribute to this repo, Can you please assign me a task? I can assure you that I can put a solution in simpler words by understanding the algorithm.
