### ISSUE TITLE
 Valid Parentheses

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#34]
Given a string `input` containing just the characters '(', ')', '{', '}', '[' and ']'. 

Check if the `input` string is valid or not.

The string is valid only if 

- Open brackets must be closed by the same type of brackets.
- Open brackets must be closed in the correct order.
- Every close bracket has a corresponding open bracket of the same type.

**Comment by mallikpramod** [comment]
please assign this problem to me

**Comment by arungudelli** [comment]
@mallikpramod please complete the first issue then we can proceed

**Comment by Yukino2002** [comment]
Hey, sorry for the error. Could you assign me the issue?

**Comment by botketan** [comment]
Can you assign this to me

**Comment by botketan** [comment]
@arungudelli can you assign me this?

**Comment by avishi-bafna** [comment]
@arungudelli I would like to work on this issue. Can you please assign me this?

**Comment by Blaize99** [comment]
Could you please assign me this issue. I am interested to work on this issue

**Comment by arungudelli** [comment]
@Blaize99 Read the contributing guidelines and start working.. Let me know if you have any questions

**Comment by Blaize99** [comment]
In which file are the codes stored

**Comment by arungudelli** [comment]
@Blaize99 

Please read the contributing guidelines
https://github.com/arungudelli/python.shiksha/blob/11b163684c7471e66137f2292b6d069a290d8874/CONTRIBUTING.md

**Comment by Blaize99** [comment]
I have made the PR please verify

**Comment by arungudelli** [comment]
@AbhignyaTayi Please work on this..

**Comment by ioannisee** [comment]
I want to work on this project

**Comment by abm4github** [comment]
Hi @arungudelli , 
If its pending yet, please assign it to me
