### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#37]
Given an array of strings, find the longest common prefix string.

If there is no common prefix, return an empty string "".

**Assumption:**

- 1 <= stringsArray.length <= 200
- 0 <= stringsArray[i].length <= 200
- stringsArray[i] consists of only lowercase English letters.

**Example:**

```
Input: strs = ["flower","flow","flight"]
Output: "fl"
```

**Comment by Shubhi-Paul** [comment]
can you assign me this ?
