### ISSUE TITLE
Contains Duplicate

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#38]
Given an integer array of numbers, return `true` if any number appears **at least twice** in the array, and return `false` if every element is distinct.

**Assumptions:**

- 1 <= nums.length <= 105
- -109 <= nums[i] <= 109

```
Input: nums = [1,2,3,1]
Output: true
```

```
Input: nums = [1,2,3,4]
Output: false
```

**Comment by bubblecode76** [comment]
hi i would like to work on this, could you pls assign this to me?

**Comment by arungudelli** [comment]
@bubblecode76 Sure.. 

Please read the [Contributing Guidelines](https://github.com/arungudelli/python.shiksha/blob/ed4e70bf28fe8d9967f5918228eb033944d5feae/CONTRIBUTING.md)

Join the [Discord](https://discord.com/invite/VTP7csbcCG) channel.

**Comment by arungudelli** [comment]
@bubblecode76 Will you able to contribute?

**Comment by bubblecode76** [comment]
yes i can
