### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#41]
Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.

**Constraints:**

-231 <= x <= 231 - 1

**Comment by NyanCyanide** [comment]
Can I work on this?

**Comment by arungudelli** [comment]
@NyanCyanide 

Please read the [Contributing Guidelines](https://github.com/arungudelli/python.shiksha/blob/ed4e70bf28fe8d9967f5918228eb033944d5feae/CONTRIBUTING.md)

Join the [Discord](https://discord.com/invite/VTP7csbcCG) channel to discuss further

**Comment by cyrilckurian** [comment]
@arungudelli I would like to contribute to this issue, can you assign me ?

**Comment by arungudelli** [comment]
@cyrilckurian Please read the [contributing guidelines](https://github.com/arungudelli/python.shiksha/blob/178bc6f74bf9fc8e121e26a394ad07ff81a0c77e/CONTRIBUTING.md).. 

And do not simply write down the soultions. 

Please explain the different approaches so that it will be helpful to others.

**Comment by Blaize99** [comment]
If this issue is still open can you assign me this issue.
