### ISSUE TITLE
FizzBuzz Python

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#48]
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i (as a string) if none of the above conditions are true.

**Comment by rk-1620** [comment]
@arungudelli I would like to work on this. Please assign it to me.

**Comment by arungudelli** [comment]
@rk-1620  Please read the contributing guidelines 

https://github.com/arungudelli/python.shiksha/blob/f2e70e57e90988b3db839041a472ea6db3a1b262/CONTRIBUTING.md

Let me know if you can explain the soultion in simple english. 

https://python.shiksha/problems/string-anagram-python/

**Comment by smitioswal** [comment]
Please assign this to me @arungudelli

**Comment by Harikrishna3** [comment]
we can add if else condition I can do it can you assign it for me
