### ISSUE TITLE
Unique Number of Occurrences

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#49]
Given an array of integers arr, return true if the number of occurrences of each value in the array is unique, or false otherwise.

https://leetcode.com/problems/unique-number-of-occurrences/

**Comment by ElectricPlant19** [comment]
can you assign this to me

**Comment by arungudelli** [comment]
Read contributing guidelines and fork the repository and start working.. let me know if you have any queries

https://github.com/arungudelli/python.shiksha/blob/11b163684c7471e66137f2292b6d069a290d8874/CONTRIBUTING.md

**Comment by ElectricPlant19** [comment]
> Read contributing guidelines and fork the repository and start working.. let me know if you have any queries
> 
> https://github.com/arungudelli/python.shiksha/blob/11b163684c7471e66137f2292b6d069a290d8874/CONTRIBUTING.md

i am in the root folder but typing npm install shows command not found

**Comment by arungudelli** [comment]
@ElectricPlant19 you need to install node and npm I guess

**Comment by dayitachaudhuri** [comment]
Hi @arungudelli If this issue is still open, I would like to work on it. I have already read the guidelines.
