### ISSUE TITLE
Merge Two Sorted Lists Python

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#50]
You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

https://leetcode.com/problems/merge-two-sorted-lists/

**Comment by JatinSingh08** [comment]
Hey @arungudelli , Please assign this to me.

**Comment by bhoomitri4** [comment]
Hey this is me again! Commenting here as asked to. would like to do this one . Kindly assign!

**Comment by arungudelli** [comment]
@bhoomitri4 Read the guidelines 

https://github.com/arungudelli/python.shiksha/blob/f2e70e57e90988b3db839041a472ea6db3a1b262/CONTRIBUTING.md

And look at the sample article 

https://python.shiksha/problems/string-anagram-python/

Let me know if you can able to explain the soultion

**Comment by arungudelli** [comment]
@JatinSingh08 Are you ok work on https://github.com/arungudelli/python.shiksha/issues/49 ?

**Comment by bhoomitri4** [comment]
Do you want me to explain the solution in simple english of the main problem statement of merging the lists here in the comments itself?

**Comment by arungudelli** [comment]
You need to write the explanation in the article.. read the contributing guidelines i have provided the sample article

**Comment by bhoomitri4** [comment]
ok I have read and will do so !!

**Comment by ShubhamShakyawal** [comment]
@arungudelli Please assign me. I would like to work on this

**Comment by bhoomitri4** [comment]
I did what was asked to do. Please review that and merge the PR if all is good!! thank you.

**Comment by Pranjal2870** [comment]
Please assign me. I would like to work on this.
