### ISSUE TITLE
3277503: How to read a file line-by-line into a list in Python

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#51]
Write a detailed tutorial to read a file line by line into a list in Python 

Refer following stackoverflow link

https://stackoverflow.com/questions/3277503/how-to-read-a-file-line-by-line-into-a-list

Read the contributing guidelines
https://github.com/arungudelli/python.shiksha/blob/f2e70e57e90988b3db839041a472ea6db3a1b262/CONTRIBUTING.md

Have a look at the sample article.

https://python.shiksha/tips/check-substring-in-string_python/

**Comment by pavankumarraju13** [comment]
@arungudelli  can you assign this to me

**Comment by botketan** [comment]
@arungudelli  I can do this can you assign me this?

**Comment by arungudelli** [comment]
@pavankumarraju13 Please Read the contributing guidelines and sample article and start working..

**Comment by arungudelli** [comment]
@botketan 

Can u work on
https://github.com/arungudelli/python.shiksha/issues/56 ?

**Comment by pavankumarraju13** [comment]
@arungudelli 
![Screenshot (566)](https://user-images.githubusercontent.com/77791888/195057532-4b4d2706-4e7d-45fd-ae7a-ce8df60fb9c8.png)
Getting error how to start npm .Could you please help me out?

**Comment by arungudelli** [comment]
@pavankumarraju13 

Run `npm install` in the root directory it will install required `node_modules` then you have to run the application using `npm run start`. 

You should be able to see `node_modules` folder inside root directory after running `npm install`

**Comment by arungudelli** [comment]
@pavankumarraju13 Let me know if you face any issues

**Comment by pavankumarraju13** [comment]
@arungudelli Thank you, sure got it.

**Comment by pavankumarraju13** [comment]
@arungudelli  i add md file.
i created pull request it shows atleast one review needed to merge. could you please review the work and what are changes needed can i know?
