### ISSUE TITLE
1720421 : How do I concatenate two lists in Python?

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/python.shiksha#56]
https://stackoverflow.com/questions/1720421/how-do-i-concatenate-two-lists-in-python

Write a detailed tutorial about concatenate two lists in Python?

Refer following stackoverflow link

https://stackoverflow.com/questions/1720421/how-do-i-concatenate-two-lists-in-python

Read the contributing guidelines
https://github.com/arungudelli/python.shiksha/blob/f2e70e57e90988b3db839041a472ea6db3a1b262/CONTRIBUTING.md

Have a look at the sample article.

https://python.shiksha/tips/check-substring-in-string_python/

File format:
https://github.com/arungudelli/python.shiksha/blob/main/content/en/tips/check-substring-in-string_python.md

**Comment by poorvaditya18** [comment]
Hey, I can work on this please assign this to me.

**Comment by arungudelli** [comment]
@AbhignyaTayi Please work on this..
