### ISSUE TITLE
Code for some algorithms in Numerical Computing

### ISSUE THREAD

**Issue by SyedSaad-07** [arungudelli/python.shiksha#68]
## Summary

Python code of algorithms in NC.
### Basic example

Example: Euler_Method, Lagrange_Interpolation, Trapezoidal etc.

**Comment by SyedSaad-07** [comment]
Kindly assign this issue to me.

**Comment by arungudelli** [comment]
@SyedSaad-07 Go though the contributig guidelines and create pull request

https://github.com/arungudelli/python.shiksha/blob/11b163684c7471e66137f2292b6d069a290d8874/CONTRIBUTING.md

**Comment by SyedSaad-07** [comment]
Ok, that.s great.

**Comment by SyedSaad-07** [comment]
I created a pull request. And resolve the issue I opened.
Kindly merge into a repo.

**Comment by Technic143** [comment]
Hello colleagues.
Some algorithms exist, can we use them? E.g.:
import numpy as np
import matplotlib.pyplot as plt

#1
_def euler(F, u0, tau, T):
    N_t = int(round(T/tau))
    F_ = lambda t, u: np.asarray(F(t, u))
    t = np.linspace(0, N_t*tau, N_t+1)
    u = np.zeros((N_t+1, len(u0)))
    u[0] = np.array(u0)
    for n in range(N_t):
        u[n+1] = u[n] + tau*F_(t[n], u[n])_

    return u, t

#2 
_def backward_euler(F, u0, tau, T):
    from scipy import optimize
    N_t = int(round(T/tau))
    F_ = lambda t, u: np.asarray(F(t, u))
    t = np.linspace(0, N_t*tau, N_t+1)
    u = np.zeros((N_t+1, len(u0)))
    u[0] = np.array(u0)

    def Phi(z, t, v):
        return z - tau*F_(t, z) - v
    
    for n in range(N_t):
        u[n+1] = optimize.fsolve(Phi, u[n], args=(t[n], u[n]))

    return u, t_
